---

- name: copy files 
  copy:
    src: copy_file/
    dest: "{{graylog_dir}}"
    owner: cloud
    group: root
    mode: 0775
    backup: yes

- name: install docker and docker-compose
  apt:
    pkg: 
      - docker.io
      - docker-compose
    update_cache: yes

- name: add user docker
  shell: usermod -aG docker {{home_user}}

- name: deploy Docker Compose
  docker_compose:
    project_src: "{{graylog_dir}}"
    files:
      - docker-compose.yml

