version: '3.7'
services:
  web:
    image: 'gitlab/gitlab-ce:14.10.0-ce.0'
    restart: always
    hostname: 'les-iti-git-1'
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://les-iti-git-1'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/home/cloud/opt_gitlab/config:/etc/gitlab'
      - '/home/cloud/opt_gitlab/logs:/var/log/gitlab'
      - '/home/cloud/opt_gitlab/data:/var/opt/gitlab'
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner    
    restart: always
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '/home/cloud/opt_gitlab/gitlab-runner:/etc/gitlab-runner'

