[[servers]]
host = "les-iti-freeipa.les-at-consulting.ru"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = true
bind_dn = "uid=grafana,cn=users,cn=accounts,dc=les-at-consulting,dc=ru"
bind_password = "131384"
search_filter = "(uid=%s)"
search_base_dns = ["cn=users,cn=accounts,dc=les-at-consulting,dc=ru"]
group_search_base_dns = ["cn=groups,cn=accounts,dc=les-at-consulting,dc=ru"]


[servers.attributes]
name = "givenName"
surname = "sn"
username = "uid"
member_of = "memberOf"
email =  "mail"


[[servers.group_mappings]]
group_dn = "cn=grafana-admins,cn=groups,cn=accounts,dc=les-at-consulting,dc=ru"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "cn=grafana-editors,cn=groups,cn=accounts,dc=les-at-consulting,dc=ru"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"
