version: '3'
services:
    # MongoDB: https://hub.docker.com/_/mongo/
    mongo:
      image: mongo:4.2
      volumes:
        - /home/cloud/opt_graylog/mongo-volume:/data/db
        - /home/cloud/opt_graylog/init-mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      networks:
        - greylog_net
    # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
    elasticsearch:
      image: elasticsearch:7.17.0
      environment:
        - http.host=0.0.0.0
        - transport.host=localhost
        - network.host=0.0.0.0
        - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - /home/cloud/opt_graylog/elastic:/usr/share/elasticsearch/data
#      deploy:
#        resources:
#          limits:
#            memory: 1g
      networks:
        - greylog_net
    # Graylog: https://hub.docker.com/r/graylog/graylog/
    graylog:
      image: graylog/graylog:4.2
      hostname: 'graylog_node1'
      container_name: graylog_node1
      volumes:
      #  - /home/kzuykov/graylog-build/journal:/usr/share/graylog/data/journal
        - graylog_data:/usr/share/graylog/data
      #  - '/home/kzuykov/graylog-build/_data:/usr/share/graylog/data'
        - /home/cloud/opt_graylog/node-id:/usr/share/graylog/data/config/node-id
      #  - /home/kzuykov/graylog-build/data3/journal:/usr/share/graylog/data/journal
      environment:
        # CHANGE ME (must be at least 16 characters)!
        - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
        # Password: admin
        - GRAYLOG_ROOT_PASSWORD_SHA2=d99f3f517b6fcb3d0df6570f255f57ba6b21ab7fc56d890b54503686d2613733
        - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
      networks:
        - greylog_net
      restart: always
      depends_on:
        - mongo
        - elasticsearch
      ports:
        # Graylog web interface and REST API
        - 9000:9000
        # Syslog TCP
        - 1514:1514
        # Syslog UDP
        - 1514:1514/udp
        # GELF TCP
        - 12201:12201
        # GELF UDP
        - 12201:12201/udp
        - 5555:5555
#        - 2323:2323
networks:
#Internal-only network for proper nginx proxying and ssh
  greylog_net:
    driver: bridge
#    enable_ipv6: true
#    internal: false
    ipam:
      driver: default
      config:
        - subnet: 172.16.237.0/24
#       - subnet: 2001:3984:3989::/64
volumes:
  graylog_data:
    driver: local
