main: 
  label: 'FreeIPA'
  host: 'les-iti-freeipa.les-at-consulting.ru'
  port: 389
  uid: 'uid'
  method: 'tls'
  bind_dn: 'uid=gitlab,cn=users,cn=accounts,dc=les-at-consulting, dc=ru'
  password: '131384'
  encryption: 'plain'
  base: 'cn=accounts,dc=les-at-consulting,dc=ru'
  verify_certificates: false
  attributes:
    username: ['uid']
    email: ['mail']
    name: 'displayName'
    first_name: 'givenName'
    last_name: 'sn'
