---

- name: copy-files 
  copy:
    src: copy_file/
    dest: "{{exporter_dir}}"
    owner: cloud
    group: root
    mode: 0775
    backup: yes

- name: copy-service 
  copy:
    src: copy_service/
    dest: "{{exporter_service_dir}}"
    owner: cloud
    group: root
    mode: 0775
    backup: yes

- name: Add the user node_exporter
  user:
    name: node_exporter
    shell: /bin/false
    system: yes

- name: enabled start node-exporter service
  systemd:
    daemon_reload: yes
    name: node_exporter
    state: started
    enabled: yes
#  become: yes
  become_user: root 
